package com.briup.crm.bean;

public class CstActivity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_activity.atv_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long atvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_activity.atv_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String atvCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_activity.atv_place
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String atvPlace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_activity.atv_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String atvTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_activity.atv_memo
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String atvMemo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_activity.atv_cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long atvCustId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_activity.atv_id
     *
     * @return the value of cst_activity.atv_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getAtvId() {
        return atvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_activity.atv_id
     *
     * @param atvId the value for cst_activity.atv_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setAtvId(Long atvId) {
        this.atvId = atvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_activity.atv_cust_name
     *
     * @return the value of cst_activity.atv_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getAtvCustName() {
        return atvCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_activity.atv_cust_name
     *
     * @param atvCustName the value for cst_activity.atv_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setAtvCustName(String atvCustName) {
        this.atvCustName = atvCustName == null ? null : atvCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_activity.atv_place
     *
     * @return the value of cst_activity.atv_place
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getAtvPlace() {
        return atvPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_activity.atv_place
     *
     * @param atvPlace the value for cst_activity.atv_place
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setAtvPlace(String atvPlace) {
        this.atvPlace = atvPlace == null ? null : atvPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_activity.atv_title
     *
     * @return the value of cst_activity.atv_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getAtvTitle() {
        return atvTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_activity.atv_title
     *
     * @param atvTitle the value for cst_activity.atv_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setAtvTitle(String atvTitle) {
        this.atvTitle = atvTitle == null ? null : atvTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_activity.atv_memo
     *
     * @return the value of cst_activity.atv_memo
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getAtvMemo() {
        return atvMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_activity.atv_memo
     *
     * @param atvMemo the value for cst_activity.atv_memo
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setAtvMemo(String atvMemo) {
        this.atvMemo = atvMemo == null ? null : atvMemo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_activity.atv_cust_id
     *
     * @return the value of cst_activity.atv_cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getAtvCustId() {
        return atvCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_activity.atv_cust_id
     *
     * @param atvCustId the value for cst_activity.atv_cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setAtvCustId(Long atvCustId) {
        this.atvCustId = atvCustId;
    }
}