package com.briup.crm.bean;

public class CstCustomer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_region
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custRegion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_manager_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long custManagerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_manager_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custManagerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_level_label
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custLevelLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_satisfy
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Integer custSatisfy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_credit
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Integer custCredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_addr
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_zip
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custZip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_fax
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custFax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_website
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custWebsite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_licence_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custLicenceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_chieftain
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custChieftain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_bankroll
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Float custBankroll;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_turnover
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Float custTurnover;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_bank
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custBank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_bank_account
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custBankAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_local_tax_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custLocalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_national_tax_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custNationalTaxNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_customer.cust_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String custStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_id
     *
     * @return the value of cst_customer.cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_id
     *
     * @param custId the value for cst_customer.cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustId(Long custId) {
        this.custId = custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_name
     *
     * @return the value of cst_customer.cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_name
     *
     * @param custName the value for cst_customer.cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_region
     *
     * @return the value of cst_customer.cust_region
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustRegion() {
        return custRegion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_region
     *
     * @param custRegion the value for cst_customer.cust_region
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustRegion(String custRegion) {
        this.custRegion = custRegion == null ? null : custRegion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_manager_id
     *
     * @return the value of cst_customer.cust_manager_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getCustManagerId() {
        return custManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_manager_id
     *
     * @param custManagerId the value for cst_customer.cust_manager_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustManagerId(Long custManagerId) {
        this.custManagerId = custManagerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_manager_name
     *
     * @return the value of cst_customer.cust_manager_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustManagerName() {
        return custManagerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_manager_name
     *
     * @param custManagerName the value for cst_customer.cust_manager_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustManagerName(String custManagerName) {
        this.custManagerName = custManagerName == null ? null : custManagerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_level_label
     *
     * @return the value of cst_customer.cust_level_label
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustLevelLabel() {
        return custLevelLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_level_label
     *
     * @param custLevelLabel the value for cst_customer.cust_level_label
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustLevelLabel(String custLevelLabel) {
        this.custLevelLabel = custLevelLabel == null ? null : custLevelLabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_satisfy
     *
     * @return the value of cst_customer.cust_satisfy
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Integer getCustSatisfy() {
        return custSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_satisfy
     *
     * @param custSatisfy the value for cst_customer.cust_satisfy
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustSatisfy(Integer custSatisfy) {
        this.custSatisfy = custSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_credit
     *
     * @return the value of cst_customer.cust_credit
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Integer getCustCredit() {
        return custCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_credit
     *
     * @param custCredit the value for cst_customer.cust_credit
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustCredit(Integer custCredit) {
        this.custCredit = custCredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_addr
     *
     * @return the value of cst_customer.cust_addr
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustAddr() {
        return custAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_addr
     *
     * @param custAddr the value for cst_customer.cust_addr
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustAddr(String custAddr) {
        this.custAddr = custAddr == null ? null : custAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_zip
     *
     * @return the value of cst_customer.cust_zip
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustZip() {
        return custZip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_zip
     *
     * @param custZip the value for cst_customer.cust_zip
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustZip(String custZip) {
        this.custZip = custZip == null ? null : custZip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_tel
     *
     * @return the value of cst_customer.cust_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_tel
     *
     * @param custTel the value for cst_customer.cust_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_fax
     *
     * @return the value of cst_customer.cust_fax
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustFax() {
        return custFax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_fax
     *
     * @param custFax the value for cst_customer.cust_fax
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustFax(String custFax) {
        this.custFax = custFax == null ? null : custFax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_website
     *
     * @return the value of cst_customer.cust_website
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustWebsite() {
        return custWebsite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_website
     *
     * @param custWebsite the value for cst_customer.cust_website
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustWebsite(String custWebsite) {
        this.custWebsite = custWebsite == null ? null : custWebsite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_licence_no
     *
     * @return the value of cst_customer.cust_licence_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustLicenceNo() {
        return custLicenceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_licence_no
     *
     * @param custLicenceNo the value for cst_customer.cust_licence_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustLicenceNo(String custLicenceNo) {
        this.custLicenceNo = custLicenceNo == null ? null : custLicenceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_chieftain
     *
     * @return the value of cst_customer.cust_chieftain
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustChieftain() {
        return custChieftain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_chieftain
     *
     * @param custChieftain the value for cst_customer.cust_chieftain
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustChieftain(String custChieftain) {
        this.custChieftain = custChieftain == null ? null : custChieftain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_bankroll
     *
     * @return the value of cst_customer.cust_bankroll
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Float getCustBankroll() {
        return custBankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_bankroll
     *
     * @param custBankroll the value for cst_customer.cust_bankroll
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustBankroll(Float custBankroll) {
        this.custBankroll = custBankroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_turnover
     *
     * @return the value of cst_customer.cust_turnover
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Float getCustTurnover() {
        return custTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_turnover
     *
     * @param custTurnover the value for cst_customer.cust_turnover
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustTurnover(Float custTurnover) {
        this.custTurnover = custTurnover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_bank
     *
     * @return the value of cst_customer.cust_bank
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustBank() {
        return custBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_bank
     *
     * @param custBank the value for cst_customer.cust_bank
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustBank(String custBank) {
        this.custBank = custBank == null ? null : custBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_bank_account
     *
     * @return the value of cst_customer.cust_bank_account
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustBankAccount() {
        return custBankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_bank_account
     *
     * @param custBankAccount the value for cst_customer.cust_bank_account
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustBankAccount(String custBankAccount) {
        this.custBankAccount = custBankAccount == null ? null : custBankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_local_tax_no
     *
     * @return the value of cst_customer.cust_local_tax_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustLocalTaxNo() {
        return custLocalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_local_tax_no
     *
     * @param custLocalTaxNo the value for cst_customer.cust_local_tax_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustLocalTaxNo(String custLocalTaxNo) {
        this.custLocalTaxNo = custLocalTaxNo == null ? null : custLocalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_national_tax_no
     *
     * @return the value of cst_customer.cust_national_tax_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustNationalTaxNo() {
        return custNationalTaxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_national_tax_no
     *
     * @param custNationalTaxNo the value for cst_customer.cust_national_tax_no
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustNationalTaxNo(String custNationalTaxNo) {
        this.custNationalTaxNo = custNationalTaxNo == null ? null : custNationalTaxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_customer.cust_status
     *
     * @return the value of cst_customer.cust_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getCustStatus() {
        return custStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_customer.cust_status
     *
     * @param custStatus the value for cst_customer.cust_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setCustStatus(String custStatus) {
        this.custStatus = custStatus == null ? null : custStatus.trim();
    }
}