package com.briup.crm.bean;

public class CstLinkman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long lkmId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long lkmCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String lkmName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_sex
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String lkmSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_postion
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String lkmPostion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String lkmTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_mobile
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String lkmMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_linkman.lkm_memo
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String lkmMemo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_id
     *
     * @return the value of cst_linkman.lkm_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getLkmId() {
        return lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_id
     *
     * @param lkmId the value for cst_linkman.lkm_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmId(Long lkmId) {
        this.lkmId = lkmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_cust_id
     *
     * @return the value of cst_linkman.lkm_cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getLkmCustId() {
        return lkmCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_cust_id
     *
     * @param lkmCustId the value for cst_linkman.lkm_cust_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmCustId(Long lkmCustId) {
        this.lkmCustId = lkmCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_name
     *
     * @return the value of cst_linkman.lkm_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getLkmName() {
        return lkmName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_name
     *
     * @param lkmName the value for cst_linkman.lkm_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmName(String lkmName) {
        this.lkmName = lkmName == null ? null : lkmName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_sex
     *
     * @return the value of cst_linkman.lkm_sex
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getLkmSex() {
        return lkmSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_sex
     *
     * @param lkmSex the value for cst_linkman.lkm_sex
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmSex(String lkmSex) {
        this.lkmSex = lkmSex == null ? null : lkmSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_postion
     *
     * @return the value of cst_linkman.lkm_postion
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getLkmPostion() {
        return lkmPostion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_postion
     *
     * @param lkmPostion the value for cst_linkman.lkm_postion
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmPostion(String lkmPostion) {
        this.lkmPostion = lkmPostion == null ? null : lkmPostion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_tel
     *
     * @return the value of cst_linkman.lkm_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getLkmTel() {
        return lkmTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_tel
     *
     * @param lkmTel the value for cst_linkman.lkm_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmTel(String lkmTel) {
        this.lkmTel = lkmTel == null ? null : lkmTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_mobile
     *
     * @return the value of cst_linkman.lkm_mobile
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getLkmMobile() {
        return lkmMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_mobile
     *
     * @param lkmMobile the value for cst_linkman.lkm_mobile
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmMobile(String lkmMobile) {
        this.lkmMobile = lkmMobile == null ? null : lkmMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_linkman.lkm_memo
     *
     * @return the value of cst_linkman.lkm_memo
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getLkmMemo() {
        return lkmMemo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_linkman.lkm_memo
     *
     * @param lkmMemo the value for cst_linkman.lkm_memo
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setLkmMemo(String lkmMemo) {
        this.lkmMemo = lkmMemo == null ? null : lkmMemo.trim();
    }
}