package com.briup.crm.bean;

public class CstService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long svrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_type
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_request
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrRequest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_dispose
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrDispose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_handle
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrHandle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_result
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cst_service.svr_satisfy
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String svrSatisfy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_id
     *
     * @return the value of cst_service.svr_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getSvrId() {
        return svrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_id
     *
     * @param svrId the value for cst_service.svr_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrId(Long svrId) {
        this.svrId = svrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_type
     *
     * @return the value of cst_service.svr_type
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrType() {
        return svrType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_type
     *
     * @param svrType the value for cst_service.svr_type
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrType(String svrType) {
        this.svrType = svrType == null ? null : svrType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_title
     *
     * @return the value of cst_service.svr_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrTitle() {
        return svrTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_title
     *
     * @param svrTitle the value for cst_service.svr_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrTitle(String svrTitle) {
        this.svrTitle = svrTitle == null ? null : svrTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_cust_name
     *
     * @return the value of cst_service.svr_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrCustName() {
        return svrCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_cust_name
     *
     * @param svrCustName the value for cst_service.svr_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrCustName(String svrCustName) {
        this.svrCustName = svrCustName == null ? null : svrCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_status
     *
     * @return the value of cst_service.svr_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrStatus() {
        return svrStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_status
     *
     * @param svrStatus the value for cst_service.svr_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrStatus(String svrStatus) {
        this.svrStatus = svrStatus == null ? null : svrStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_request
     *
     * @return the value of cst_service.svr_request
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrRequest() {
        return svrRequest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_request
     *
     * @param svrRequest the value for cst_service.svr_request
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrRequest(String svrRequest) {
        this.svrRequest = svrRequest == null ? null : svrRequest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_dispose
     *
     * @return the value of cst_service.svr_dispose
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrDispose() {
        return svrDispose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_dispose
     *
     * @param svrDispose the value for cst_service.svr_dispose
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrDispose(String svrDispose) {
        this.svrDispose = svrDispose == null ? null : svrDispose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_handle
     *
     * @return the value of cst_service.svr_handle
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrHandle() {
        return svrHandle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_handle
     *
     * @param svrHandle the value for cst_service.svr_handle
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrHandle(String svrHandle) {
        this.svrHandle = svrHandle == null ? null : svrHandle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_result
     *
     * @return the value of cst_service.svr_result
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrResult() {
        return svrResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_result
     *
     * @param svrResult the value for cst_service.svr_result
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrResult(String svrResult) {
        this.svrResult = svrResult == null ? null : svrResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cst_service.svr_satisfy
     *
     * @return the value of cst_service.svr_satisfy
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getSvrSatisfy() {
        return svrSatisfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cst_service.svr_satisfy
     *
     * @param svrSatisfy the value for cst_service.svr_satisfy
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setSvrSatisfy(String svrSatisfy) {
        this.svrSatisfy = svrSatisfy == null ? null : svrSatisfy.trim();
    }
}