package com.briup.crm.bean;

public class SalChance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Long chcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_source
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcCustName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_rate
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Integer chcRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_linkman
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcLinkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_addr
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_desc
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_create_by
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcCreateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_due_to
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private String chcDueTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sal_chance.chc_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    private Integer chcStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_id
     *
     * @return the value of sal_chance.chc_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Long getChcId() {
        return chcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_id
     *
     * @param chcId the value for sal_chance.chc_id
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcId(Long chcId) {
        this.chcId = chcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_source
     *
     * @return the value of sal_chance.chc_source
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcSource() {
        return chcSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_source
     *
     * @param chcSource the value for sal_chance.chc_source
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcSource(String chcSource) {
        this.chcSource = chcSource == null ? null : chcSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_cust_name
     *
     * @return the value of sal_chance.chc_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcCustName() {
        return chcCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_cust_name
     *
     * @param chcCustName the value for sal_chance.chc_cust_name
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcCustName(String chcCustName) {
        this.chcCustName = chcCustName == null ? null : chcCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_title
     *
     * @return the value of sal_chance.chc_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcTitle() {
        return chcTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_title
     *
     * @param chcTitle the value for sal_chance.chc_title
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcTitle(String chcTitle) {
        this.chcTitle = chcTitle == null ? null : chcTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_rate
     *
     * @return the value of sal_chance.chc_rate
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Integer getChcRate() {
        return chcRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_rate
     *
     * @param chcRate the value for sal_chance.chc_rate
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcRate(Integer chcRate) {
        this.chcRate = chcRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_linkman
     *
     * @return the value of sal_chance.chc_linkman
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcLinkman() {
        return chcLinkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_linkman
     *
     * @param chcLinkman the value for sal_chance.chc_linkman
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcLinkman(String chcLinkman) {
        this.chcLinkman = chcLinkman == null ? null : chcLinkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_tel
     *
     * @return the value of sal_chance.chc_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcTel() {
        return chcTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_tel
     *
     * @param chcTel the value for sal_chance.chc_tel
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcTel(String chcTel) {
        this.chcTel = chcTel == null ? null : chcTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_addr
     *
     * @return the value of sal_chance.chc_addr
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcAddr() {
        return chcAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_addr
     *
     * @param chcAddr the value for sal_chance.chc_addr
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcAddr(String chcAddr) {
        this.chcAddr = chcAddr == null ? null : chcAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_desc
     *
     * @return the value of sal_chance.chc_desc
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcDesc() {
        return chcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_desc
     *
     * @param chcDesc the value for sal_chance.chc_desc
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcDesc(String chcDesc) {
        this.chcDesc = chcDesc == null ? null : chcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_create_by
     *
     * @return the value of sal_chance.chc_create_by
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcCreateBy() {
        return chcCreateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_create_by
     *
     * @param chcCreateBy the value for sal_chance.chc_create_by
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcCreateBy(String chcCreateBy) {
        this.chcCreateBy = chcCreateBy == null ? null : chcCreateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_due_to
     *
     * @return the value of sal_chance.chc_due_to
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getChcDueTo() {
        return chcDueTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_due_to
     *
     * @param chcDueTo the value for sal_chance.chc_due_to
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcDueTo(String chcDueTo) {
        this.chcDueTo = chcDueTo == null ? null : chcDueTo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sal_chance.chc_status
     *
     * @return the value of sal_chance.chc_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Integer getChcStatus() {
        return chcStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sal_chance.chc_status
     *
     * @param chcStatus the value for sal_chance.chc_status
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setChcStatus(Integer chcStatus) {
        this.chcStatus = chcStatus;
    }
}