package com.briup.crm.bean;

import java.util.ArrayList;
import java.util.List;

public class SalPlanExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public SalPlanExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlaIdIsNull() {
            addCriterion("pla_id is null");
            return (Criteria) this;
        }

        public Criteria andPlaIdIsNotNull() {
            addCriterion("pla_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlaIdEqualTo(Long value) {
            addCriterion("pla_id =", value, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdNotEqualTo(Long value) {
            addCriterion("pla_id <>", value, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdGreaterThan(Long value) {
            addCriterion("pla_id >", value, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdGreaterThanOrEqualTo(Long value) {
            addCriterion("pla_id >=", value, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdLessThan(Long value) {
            addCriterion("pla_id <", value, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdLessThanOrEqualTo(Long value) {
            addCriterion("pla_id <=", value, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdIn(List<Long> values) {
            addCriterion("pla_id in", values, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdNotIn(List<Long> values) {
            addCriterion("pla_id not in", values, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdBetween(Long value1, Long value2) {
            addCriterion("pla_id between", value1, value2, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaIdNotBetween(Long value1, Long value2) {
            addCriterion("pla_id not between", value1, value2, "plaId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdIsNull() {
            addCriterion("pla_chc_id is null");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdIsNotNull() {
            addCriterion("pla_chc_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdEqualTo(Long value) {
            addCriterion("pla_chc_id =", value, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdNotEqualTo(Long value) {
            addCriterion("pla_chc_id <>", value, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdGreaterThan(Long value) {
            addCriterion("pla_chc_id >", value, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdGreaterThanOrEqualTo(Long value) {
            addCriterion("pla_chc_id >=", value, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdLessThan(Long value) {
            addCriterion("pla_chc_id <", value, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdLessThanOrEqualTo(Long value) {
            addCriterion("pla_chc_id <=", value, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdIn(List<Long> values) {
            addCriterion("pla_chc_id in", values, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdNotIn(List<Long> values) {
            addCriterion("pla_chc_id not in", values, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdBetween(Long value1, Long value2) {
            addCriterion("pla_chc_id between", value1, value2, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaChcIdNotBetween(Long value1, Long value2) {
            addCriterion("pla_chc_id not between", value1, value2, "plaChcId");
            return (Criteria) this;
        }

        public Criteria andPlaTodoIsNull() {
            addCriterion("pla_todo is null");
            return (Criteria) this;
        }

        public Criteria andPlaTodoIsNotNull() {
            addCriterion("pla_todo is not null");
            return (Criteria) this;
        }

        public Criteria andPlaTodoEqualTo(String value) {
            addCriterion("pla_todo =", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoNotEqualTo(String value) {
            addCriterion("pla_todo <>", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoGreaterThan(String value) {
            addCriterion("pla_todo >", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoGreaterThanOrEqualTo(String value) {
            addCriterion("pla_todo >=", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoLessThan(String value) {
            addCriterion("pla_todo <", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoLessThanOrEqualTo(String value) {
            addCriterion("pla_todo <=", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoLike(String value) {
            addCriterion("pla_todo like", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoNotLike(String value) {
            addCriterion("pla_todo not like", value, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoIn(List<String> values) {
            addCriterion("pla_todo in", values, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoNotIn(List<String> values) {
            addCriterion("pla_todo not in", values, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoBetween(String value1, String value2) {
            addCriterion("pla_todo between", value1, value2, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaTodoNotBetween(String value1, String value2) {
            addCriterion("pla_todo not between", value1, value2, "plaTodo");
            return (Criteria) this;
        }

        public Criteria andPlaResultIsNull() {
            addCriterion("pla_result is null");
            return (Criteria) this;
        }

        public Criteria andPlaResultIsNotNull() {
            addCriterion("pla_result is not null");
            return (Criteria) this;
        }

        public Criteria andPlaResultEqualTo(String value) {
            addCriterion("pla_result =", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultNotEqualTo(String value) {
            addCriterion("pla_result <>", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultGreaterThan(String value) {
            addCriterion("pla_result >", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultGreaterThanOrEqualTo(String value) {
            addCriterion("pla_result >=", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultLessThan(String value) {
            addCriterion("pla_result <", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultLessThanOrEqualTo(String value) {
            addCriterion("pla_result <=", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultLike(String value) {
            addCriterion("pla_result like", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultNotLike(String value) {
            addCriterion("pla_result not like", value, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultIn(List<String> values) {
            addCriterion("pla_result in", values, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultNotIn(List<String> values) {
            addCriterion("pla_result not in", values, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultBetween(String value1, String value2) {
            addCriterion("pla_result between", value1, value2, "plaResult");
            return (Criteria) this;
        }

        public Criteria andPlaResultNotBetween(String value1, String value2) {
            addCriterion("pla_result not between", value1, value2, "plaResult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sal_plan
     *
     * @mbg.generated do_not_delete_during_merge Tue Jan 07 16:47:07 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sal_plan
     *
     * @mbg.generated Tue Jan 07 16:47:07 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}